
---
- name: Configure Web Servers
  hosts: web
  become: true
  roles:
    - web

- name: Configure Load Balancer
  hosts: lb
  become: true
  roles:
    - lb

- name: Configure Monitoring
  hosts: monitor
  become: true
  roles:
    - monitor
